/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AssistanceProgram = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
});
export const CommunityResource = IDL.Record({
  'name' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'resourceType' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const HealthcareService = IDL.Record({
  'contactInfo' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const InsuranceTerm = IDL.Record({
  'term' : IDL.Text,
  'definition' : IDL.Text,
});
export const Workshop = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'audience' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAssistancePrograms' : IDL.Func(
      [],
      [IDL.Vec(AssistanceProgram)],
      ['query'],
    ),
  'getCommunityResources' : IDL.Func(
      [],
      [IDL.Vec(CommunityResource)],
      ['query'],
    ),
  'getHealthcareServices' : IDL.Func(
      [],
      [IDL.Vec(HealthcareService)],
      ['query'],
    ),
  'getInsuranceTerms' : IDL.Func([], [IDL.Vec(InsuranceTerm)], ['query']),
  'getResourcesByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommunityResource)],
      ['query'],
    ),
  'getWorkshops' : IDL.Func([], [IDL.Vec(Workshop)], ['query']),
  'initializeData' : IDL.Func([], [], []),
  'searchInsuranceTerm' : IDL.Func([IDL.Text], [InsuranceTerm], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AssistanceProgram = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
  });
  const CommunityResource = IDL.Record({
    'name' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'resourceType' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const HealthcareService = IDL.Record({
    'contactInfo' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const InsuranceTerm = IDL.Record({
    'term' : IDL.Text,
    'definition' : IDL.Text,
  });
  const Workshop = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'audience' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAssistancePrograms' : IDL.Func(
        [],
        [IDL.Vec(AssistanceProgram)],
        ['query'],
      ),
    'getCommunityResources' : IDL.Func(
        [],
        [IDL.Vec(CommunityResource)],
        ['query'],
      ),
    'getHealthcareServices' : IDL.Func(
        [],
        [IDL.Vec(HealthcareService)],
        ['query'],
      ),
    'getInsuranceTerms' : IDL.Func([], [IDL.Vec(InsuranceTerm)], ['query']),
    'getResourcesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommunityResource)],
        ['query'],
      ),
    'getWorkshops' : IDL.Func([], [IDL.Vec(Workshop)], ['query']),
    'initializeData' : IDL.Func([], [], []),
    'searchInsuranceTerm' : IDL.Func([IDL.Text], [InsuranceTerm], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };